-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 10:33:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema d3h1e6gli70da7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d3h1e6gli70da7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS d3h1e6gli70da7 DEFAULT CHARACTER SET utf8 ;
USE d3h1e6gli70da7 ;

-- -----------------------------------------------------
-- Table `d3h1e6gli70da7`.`animal_perdido`
-- -----------------------------------------------------
CREATE SEQUENCE animal_perdido_seq;

CREATE TABLE IF NOT EXISTS animal_perdido (
  idanimal_perdido INT NOT NULL DEFAULT NEXTVAL ('animal_perdido_seq'),
  especie VARCHAR(45) NULL,
  caracteristicas_fisicas TEXT NULL,
  foto VARCHAR(255) NULL,
  quando DATE NULL,
  onde VARCHAR(255) NULL,
  PRIMARY KEY (idanimal_perdido))
;


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
